minolo_motor_interface:
  ros__parameters:
    serial_port: /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0
    baudrate: 115200
    self.serial_read_rate: 20
    timeout_seconds: 0.1