minolo_motor_controller:
  ros__parameters:
    wheel_diameter: 0.17
    wheels_base: 0.37
    encoder_ticks_per_rev: 90
    fixed_frame_id: odom
    robot_frame_id: base_footprint
    publish_tf: False
    odom_topic: '/odom_wheels'
    #odom_topic: '/odom'
    
    
